services:
  limboo_remote_access_api:
    container_name: limboo_remote_access_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/api
    environment:
      NODE_ENV: development
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: remote_access
      NATS_HOSTNAME: nats
      NATS_PORT: 4222
    command: ['sh', '-c', 'npm install && npm run start:dev']
    depends_on:
      - database
      - nats
    networks:
      - limboo

  database:
    image: postgres:13
    ports:
      - '5436:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    networks:
      - limboo

  nats:
    image: bitnami/nats:latest
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222
    environment:
      NATS_EXTRA_ARGS: -js
    networks:
      - limboo

networks:
  limboo:
    external: true
