version: '2'
services:
  api:
    container_name: limboo_remote_acess_api
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    command: ["npm", "run", "start:dev"]
    networks:
      - limboo

  database:
    image: postgres:13
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: remote_access
    networks:
      - limboo

  nats:
    image: bitnami/nats:latest
    ports:
      - 4222:4222
    networks:
      - limboo

networks:
  limboo:
    driver: bridge
