apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: limboo
  name: limboo-remote-access-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: limboo-remote-access-service
  template:
    metadata:
      labels:
        app: limboo-remote-access-service
    spec:
      containers:
        - name: limboo-remote-access-service
          image: registry.yuri.dev.br/limboo-remote-access-service:1.0.36
          ports:
            - containerPort: 3000
          env:
            - name: KEYCLOAK_AUTH_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: limboo-remote-access-service-secrets
                  key: KEYCLOAK_AUTH_SERVER_URL
            - name: KEYCLOAK_REALM
              valueFrom:
                secretKeyRef:
                  name: limboo-remote-access-service-secrets
                  key: KEYCLOAK_REALM
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: limboo-remote-access-service-secrets
                  key: KEYCLOAK_CLIENT_ID
            - name: KEYCLOAK_SECRET
              valueFrom:
                secretKeyRef:
                  name: limboo-remote-access-service-secrets
                  key: KEYCLOAK_SECRET
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: limboo-remote-access-service-secrets
                  key: POSTGRES_HOST
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: limboo-remote-access-service-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: limboo-remote-access-service-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: limboo-remote-access-service-secrets
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: limboo-remote-access-service-secrets
                  key: POSTGRES_DB
            - name: NATS_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: limboo-remote-access-service-secrets
                  key: NATS_HOSTNAME
            - name: NATS_PORT
              valueFrom:
                secretKeyRef:
                  name: limboo-remote-access-service-secrets
                  key: NATS_PORT
      imagePullSecrets:
        - name: registry-secret
