apiVersion: v1
kind: Service
metadata:
  name: limbo-update-server-svc
  namespace: limboo
spec:
  selector:
    app: limbo-update-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
